FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/frontend ./src/frontend

EXPOSE 8501

CMD ["sh", "-c", "streamlit run src/frontend/app.py --server.address=0.0.0.0 --server.port ${PORT:-8501}"]
