FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

COPY models/lstm_attention_unrolled.tflite ./models/lstm_attention_unrolled.tflite
COPY models/feature_scaler.pkl ./models/feature_scaler.pkl

COPY data/latest_history.parquet ./data/latest_history.parquet
COPY configs ./configs

EXPOSE 8000

CMD ["sh", "-c", "uvicorn src.api.api:app --host 0.0.0.0 --port ${PORT:-8000}"]
